### ISSUE TITLE
BluetoothAdaptor().startLeScan() is Deprecated.

### ISSUE THREAD

**Issue by moosabaloch** [adafruit/Bluefruit_LE_Connect_Android#23]
Bluefruit_LE_Connect_Android/app/src/main/java/com/adafruit/bluefruit/le/connect/ble/BleDevicesScanner.java
Line number 70 & 78
`mBluetoothAdapter.startLeScan(mLeScanCallback);` 
startLeScan() is Deprecated. 
stopLeScan() is Deprecated.

**Comment by antonio-openroad** [comment]
This project is no longer updated, but you can find the new version here: https://github.com/adafruit/Bluefruit_LE_Connect_Android_v2
It uses the newer scan API from Android 5.0 if the device supports it, or the old one for older devices.
