### ISSUE TITLE
UART RX Indications needs to enabled locally

### ISSUE THREAD

**Issue by joshingyou** [adafruit/Bluefruit_LE_Connect_Android#26]
On line 147 of BleGattExecutor.java, UART RX Indications needs to be enabled locally too, similar to 109 and 110. Otherwise, onCharacteristicChanged() never gets called back. 

Offending source code: 
https://github.com/adafruit/Bluefruit_LE_Connect_Android/blob/master/app/src/main/java/com/adafruit/bluefruit/le/connect/ble/BleGattExecutor.java#L147

Reference: 
http://stackoverflow.com/a/35985454/1518421

**Comment by antonio-openroad** [comment]
You are right, they should be enabled locally to work, but indications where not used on the project so it was not a real problem.
This codebase is no longer maintained, so it will not be fixed here but it will be taken into account for the new codebase if indications are implemented.
Thanks
