### ISSUE TITLE
How hard would it be to port this to HTTP (e.g. to use with ESP8266 Huzzah feather)?

### ISSUE THREAD

**Issue by hamishcunningham** [adafruit/Bluefruit_LE_Connect_Android#29]
Hi, Great app! I've been using it with Adabox 002 and love it!

I'd like to use this in a course on IoT I'm doing in the autumn, but we're using ESP8266... what would be involved with getting it to run (as a controller for the Adabox mini robot) over HTTP?

THanks!

**Comment by hamishcunningham** [comment]
Or, erm, how about the ESP32 (which has bluetooth)?

Cheers,

Hamish

**Comment by microbuilder** [comment]
The app is based entirely on BLE, so it would likely require a new app with HTTP planned from the start, unfortunately. Sorry we can't be more helpful in this case, but the app is targeted at a specific transport and makes a lot of HW assumptions.
