### ISSUE TITLE
Battery service displays -1%

### ISSUE THREAD

**Issue by transistor-man** [adafruit/Bluefruit_LE_Connect_Android#36]
After configuring and starting the battery service on an NRF52 bluefruit, app displays -1% battery, regardless of what blebas is set to. To duplicate this, I used the stock bleuart peripheral example, where   blebas.write(100); was used to set battery status to 100%. Included a screenshot.  Bluefruit firmware 0.8.4

![screencap](https://user-images.githubusercontent.com/9489729/44071670-a8658f80-9f58-11e8-81b7-8b929e0e4f6c.JPG)

**Comment by antonio-openroad** [comment]
Thanks for the report. 
It has been fixed on v3.0.8 and it will be soon available on GooglePlay 

This repository is no longer updated. Please report any problems that you find on the following repository: https://github.com/adafruit/Bluefruit_LE_Connect_Android_v2
