### ISSUE TITLE
discontinue/archive

### ISSUE THREAD

**Issue by ladyada** [adafruit/Bluefruit_LE_Connect_Android#37]
hiya @antonio-openroad if this repository is discontinued, lets archive it. please respond to and close all pull requests, update the readme to say its compeltely unsupported/archived and i will archive it so no more issues/PRs can be created

thanx!

**Comment by antonio-openroad** [comment]
I just finished responding and closing issues and pull requests.
I did the same for the old iOS repository: https://github.com/adafruit/Bluefruit_LE_Connect
It can be archived too.

The current repositories are:
Android: https://github.com/adafruit/Bluefruit_LE_Connect_Android_v2
iOS: https://github.com/adafruit/Bluefruit_LE_Connect_v2

**Comment by ladyada** [comment]
ok this one is now archived
